Status(
    _api= < tweepy.api.APIobjectat0x000001AD16778730 > ,
    _json=
    {"created_at": "Thu Dec 03 04:13:21 +0000 2020",
	"id": 1334349981382270976,
	"id_str": "1334349981382270976",
	"text": "test1",
	"truncated": False,
	"entities": {"hashtags": [],
	"symbols": [],
	"user_mentions": [],
	"urls": []},
	"source": "<a href="https://twitch.tv/rhyle_" rel="nofollow">rhyle_bot</a>",
	"in_reply_to_status_id": None,
	"in_reply_to_status_id_str": None,
	"in_reply_to_user_id": None,
	"in_reply_to_user_id_str": None,
	"in_reply_to_screen_name": None,
	"user": {"id": 302662769,
	"id_str": "302662769",
	"name": "Rhyle_",
	"screen_name": "Rhyle_",
	"location": "Wesley Chapel,
	FL",
	"description": "Full time automation developer,
	part time streamer. Student,
	father,
	ally. Self taught developer,
	currently learning Unity.\n\nHe/Him,
	LGBTQ+ Friendly",
	"url": "https://t.co/ld2458nZY1",
	"entities": {"url": {"urls": [{"url": "https://t.co/ld2458nZY1",
	"expanded_url": "https://twitch.tv/Rhyle_",
	"display_url": "twitch.tv/Rhyle_",
	"indices": [0,
	23]}]},
	"description": {"urls": []}},
	"protected": False,
	"followers_count": 80,
	"friends_count": 224,
	"listed_count": 3,
	"created_at": "Sat May 21 15:13:54 +0000 2011",
	"favourites_count": 829,
	"utc_offset": None,
	"time_zone": None,
	"geo_enabled": True,
	"verified": False,
	"statuses_count": 865,
	"lang": None,
	"contributors_enabled": False,
	"is_translator": False,
	"is_translation_enabled": False,
	"profile_background_color": "131516",
	"profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_tile": True,
	"profile_image_url": "http://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_image_url_https": "https://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_link_color": "009999",
	"profile_sidebar_border_color": "EEEEEE",
	"profile_sidebar_fill_color": "EFEFEF",
	"profile_text_color": "333333",
	"profile_use_background_image": True,
	"has_extended_profile": True,
	"default_profile": False,
	"default_profile_image": False,
	"following": False,
	"follow_request_sent": False,
	"notifications": False,
	"translator_type": "none"},
	"geo": None,
	"coordinates": None,
	"place": None,
	"contributors": None,
	"is_quote_status": False,
	"retweet_count": 0,
	"favorite_count": 0,
	"favorited": False,
	"retweeted": False,
	"lang": "en"},
	created_at=datetime.datetime(2020,
	12,
	3,
	4,
	13,
	21),
	id=1334349981382270976,
	id_str="1334349981382270976",
	text="test1",
	truncated=False,
	entities={"hashtags": [],
	"symbols": [],
	"user_mentions": [],
	"urls": []},
	source="rhyle_bot",
	source_url="https://twitch.tv/rhyle_",
	
in_reply_to_status_id=None,
	in_reply_to_status_id_str=None,
	in_reply_to_user_id=None,
	in_reply_to_user_id_str=None,
	in_reply_to_screen_name=None,
	author=User(_api=<tweepy.api.API object at 0x000001AD16778730>,
	_json={"id": 302662769,
	"id_str": "302662769",
	"name": "Rhyle_",
	"screen_name": "Rhyle_",
	"location": "Wesley Chapel,
	FL",
	"description": "Full time automation developer,
	part time streamer. Student,
	father,
	ally. Self taught developer,
	currently learning Unity.\n\nHe/Him,
	LGBTQ+ Friendly",
	"url": "https://t.co/ld2458nZY1",
	"entities": {"url": {"urls": [{"url": "https://t.co/ld2458nZY1",
	"expanded_url": "https://twitch.tv/Rhyle_",
	
"display_url": "twitch.tv/Rhyle_",
	"indices": [0,
	23]}]},
	"description": {"urls": []}},
	"protected": False,
	"followers_count": 80,
	"friends_count": 224,
	"listed_count": 3,
	"created_at": "Sat May 21 15:13:54 +0000 2011",
	"favourites_count": 829,
	"utc_offset": None,
	"time_zone": None,
	"geo_enabled": True,
	"verified": False,
	"statuses_count": 865,
	"lang": None,
	"contributors_enabled": False,
	"is_translator": False,
	"is_translation_enabled": False,
	"profile_background_color": "131516",
	"profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_tile": True,
	"profile_image_url": "http://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_image_url_https": "https://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_link_color": "009999",
	"profile_sidebar_border_color": "EEEEEE",
	"profile_sidebar_fill_color": "EFEFEF",
	"profile_text_color": "333333",
	"profile_use_background_image": True,
	"has_extended_profile": True,
	"default_profile": False,
	"default_profile_image": False,
	"following": False,
	"follow_request_sent": False,
	"notifications": False,
	"translator_type": "none"},
	id=302662769,
	id_str="302662769",
	name="Rhyle_",
	screen_name="Rhyle_",
	location="Wesley Chapel,
	FL",
	description="Full time automation developer,
	part time streamer. Student,
	father,
	ally. Self taught developer,
	currently learning Unity.\n\nHe/Him,
	LGBTQ+ Friendly",
	url="https://t.co/ld2458nZY1",
	entities={"url": {"urls": [{"url": "https://t.co/ld2458nZY1",
	"expanded_url": "https://twitch.tv/Rhyle_",
	"display_url": "twitch.tv/Rhyle_",
	"indices": [0,
	23]}]},
	"description": {"urls": []}},
	protected=False,
	followers_count=80,
	friends_count=224,
	listed_count=3,
	created_at=datetime.datetime(2011,
	5,
	21,
	15,
	13,
	54),
	favourites_count=829,
	utc_offset=None,
	time_zone=None,
	geo_enabled=True,
	verified=False,
	statuses_count=865,
	lang=None,
	contributors_enabled=False,
	is_translator=False,
	is_translation_enabled=False,
	profile_background_color="131516",
	profile_background_image_url="http://abs.twimg.com/images/themes/theme14/bg.gif",
	profile_background_image_url_https="https://abs.twimg.com/images/themes/theme14/bg.gif",
	profile_background_tile=True,
	profile_image_url="http://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	profile_image_url_https="https://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	profile_link_color="009999",
	profile_sidebar_border_color="EEEEEE",
	profile_sidebar_fill_color="EFEFEF",
	profile_text_color="333333",
	profile_use_background_image=True,
	has_extended_profile=True,
	default_profile=False,
	default_profile_image=False,
	following=False,
	follow_request_sent=False,
	notifications=False,
	translator_type="none"),
	user=User(_api=<tweepy.api.API object at 0x000001AD16778730>,
	_json={"id": 302662769,
	"id_str": 
"302662769",
	"name": "Rhyle_",
	"screen_name": "Rhyle_",
	"location": "Wesley Chapel,
	FL",
	"description": "Full time automation developer,
	part time streamer. Student,
	father,
	ally. Self taught developer,
	currently learning Unity.\n\nHe/Him,
	LGBTQ+ Friendly",
	
"url": "https://t.co/ld2458nZY1",
	"entities": {"url": {"urls": [{"url": "https://t.co/ld2458nZY1",
	"expanded_url": "https://twitch.tv/Rhyle_",
	"display_url": "twitch.tv/Rhyle_",
	"indices": [0,
	23]}]},
	"description": {"urls": []}},
	"protected": False,
	"followers_count": 80,
	"friends_count": 224,
	"listed_count": 3,
	"created_at": "Sat May 21 15:13:54 +0000 2011",
	"favourites_count": 829,
	"utc_offset": None,
	"time_zone": None,
	"geo_enabled": True,
	"verified": False,
	"statuses_count": 865,
	"lang": None,
	"contributors_enabled": False,
	"is_translator": False,
	"is_translation_enabled": False,
	"profile_background_color": "131516",
	"profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
	"profile_background_tile": True,
	"profile_image_url": "http://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_image_url_https": "https://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	"profile_link_color": "009999",
	"profile_sidebar_border_color": "EEEEEE",
	"profile_sidebar_fill_color": "EFEFEF",
	
"profile_text_color": "333333",
	"profile_use_background_image": True,
	"has_extended_profile": True,
	"default_profile": False,
	"default_profile_image": False,
	"following": False,
	"follow_request_sent": False,
	"notifications": False,
	"translator_type": "none"},
	id=302662769,
	id_str="302662769",
	name="Rhyle_",
	screen_name="Rhyle_",
	location="Wesley Chapel,
	FL",
	description="Full time automation developer,
	part time streamer. Student,
	father,
	ally. Self taught developer,
	currently learning Unity.\n\nHe/Him,
	LGBTQ+ 
Friendly",
	url="https://t.co/ld2458nZY1",
	entities={"url": {"urls": [{"url": "https://t.co/ld2458nZY1",
	"expanded_url": "https://twitch.tv/Rhyle_",
	"display_url": "twitch.tv/Rhyle_",
	"indices": [0,
	23]}]},
	"description": {"urls": []}},
	protected=False,
	followers_count=80,
	friends_count=224,
	listed_count=3,
	created_at=datetime.datetime(2011,
	5,
	21,
	15,
	13,
	54),
	favourites_count=829,
	utc_offset=None,
	time_zone=None,
	geo_enabled=True,
	verified=False,
	statuses_count=865,
	lang=None,
	contributors_enabled=False,
	is_translator=False,
	is_translation_enabled=False,
	profile_background_color="131516",
	profile_background_image_url="http://abs.twimg.com/images/themes/theme14/bg.gif",
	profile_background_image_url_https="https://abs.twimg.com/images/themes/theme14/bg.gif",
	profile_background_tile=True,
	profile_image_url="http://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	profile_image_url_https="https://pbs.twimg.com/profile_images/1014167507924668418/LAzKjLmf_normal.jpg",
	profile_link_color="009999",
	profile_sidebar_border_color="EEEEEE",
	profile_sidebar_fill_color="EFEFEF",
	profile_text_color="333333",
	profile_use_background_image=True,
	has_extended_profile=True,
	default_profile=False,
	default_profile_image=False,
	following=False,
	follow_request_sent=False,
	notifications=False,
	translator_type="none"),
	geo=None,
	coordinates=None,
	place=None,
	contributors=None,
	is_quote_status=False,
	
retweet_count=0,
	favorite_count=0,
	favorited=False,
	
retweeted=False,
	
lang="en")